# Generated by Django 4.0.5 on 2022-06-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='lastname_name',
            new_name='last_name',
        ),
    ]
