# Generated by Django 4.0.5 on 2022-06-15 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_lastname_name_account_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('code', models.CharField(max_length=80)),
                ('invited_from', models.CharField(max_length=80)),
                ('used', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
