# Generated by Django 4.0.5 on 2022-06-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'tax', 'verbose_name_plural': 'taxes'},
        ),
    ]
