# Generated by Django 4.0.5 on 2022-06-16 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonuses', '0001_initial'),
        ('funds', '0004_tax_directbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balance',
            name='cash_in',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='cash_out',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='directbonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bonuses.directbonus'),
        ),
        migrations.AddField(
            model_name='balance',
            name='discountbonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bonuses.discountbonus'),
        ),
        migrations.AddField(
            model_name='balance',
            name='insurance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='funds.insurance'),
        ),
        migrations.AddField(
            model_name='balance',
            name='magicbonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bonuses.magicbonus'),
        ),
        migrations.AddField(
            model_name='balance',
            name='net_balance',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='funds.payment'),
        ),
        migrations.AddField(
            model_name='balance',
            name='tax',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='funds.tax'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
