# Generated by Django 4.0.5 on 2022-06-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0001_initial'),
        ('funds', '0005_balance_account_balance_cash_in_balance_cash_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='narration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='directbonus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bonuses.directbonus'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='discountbonus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bonuses.discountbonus'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='insurance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='funds.insurance'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='magicbonus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bonuses.magicbonus'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='funds.payment'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='tax',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='funds.tax'),
        ),
    ]
