# Generated by Django 4.0.5 on 2022-06-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0002_remove_discountbonus_code_and_more'),
        ('funds', '0006_balance_narration_alter_balance_directbonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='discountbonus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bonuses.discountbonus'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='directbonus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bonuses.directbonus'),
        ),
    ]
