# Generated by Django 4.0.5 on 2022-06-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_tax_discountbonus_alter_tax_directbonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='funds.payment'),
        ),
    ]
