# Generated by Django 4.0.5 on 2022-06-16 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0003_balance_rename_payment_number_payment_payment_num_and_more'),
        ('accounts', '0003_referral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectBonus',
            fields=[
                ('ref_num', models.CharField(max_length=200, unique=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='funds.payment')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.referral')),
            ],
            options={
                'verbose_name': 'directbonus',
                'verbose_name_plural': 'directbonuses',
            },
        ),
        migrations.CreateModel(
            name='LeadershipBonus',
            fields=[
                ('rank', models.IntegerField(default=0)),
                ('level', models.CharField(max_length=200, unique=True)),
                ('incentive', models.IntegerField(default=0)),
                ('used_upto', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'leadershipbonus',
                'verbose_name_plural': 'leadershipbonuses',
            },
        ),
        migrations.CreateModel(
            name='MagicBonus',
            fields=[
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('directbonus', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='bonuses.directbonus')),
            ],
            options={
                'verbose_name': 'magicbonus',
                'verbose_name_plural': 'magicbonuses',
            },
        ),
        migrations.CreateModel(
            name='DiscountBonus',
            fields=[
                ('code', models.CharField(max_length=200, unique=True)),
                ('validity', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'discountbonus',
                'verbose_name_plural': 'discountbonuses',
            },
        ),
    ]
