# Generated by Django 4.0.5 on 2022-06-17 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_balance_narration_alter_balance_directbonus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonuses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountbonus',
            name='code',
        ),
        migrations.RemoveField(
            model_name='discountbonus',
            name='validity',
        ),
        migrations.AddField(
            model_name='discountbonus',
            name='admin_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discountbonus',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='discountbonus',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='funds.payment'),
        ),
        migrations.AddField(
            model_name='magicbonus',
            name='discountbonus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bonuses.discountbonus'),
        ),
        migrations.AlterField(
            model_name='discountbonus',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
