# Generated by Django 4.0.5 on 2022-06-17 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonuses', '0002_remove_discountbonus_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountbonus',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
